avanceCsharp/Models/Categoria.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace avanceCsharp.Models
{
    [Table("tb_categoria")]
    public class Categoria
    {
        [Key]
        public string codigo { get; set; }

        [Display(Name = "Apellido paterno")]
        public string categoria { get; set; }

}
}

avanceCsharp/Models/ErrorViewModel.cs
namespace avanceCsharp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

avanceCsharp/Models/Personal.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace avanceCsharp.Models
{
    [Table("tb_personal")]
    public class Personal
    {
        [Key]
        public string dni { get; set; }

        [Display(Name = "Apellido paterno")]
        public string ap_paterno { get; set; }

        [Display(Name = "Apellido materno")]
        public string ap_materno { get; set; }

        public string nombre { get; set; }

        public char genero { get; set; }


        
        [Display(Name = "Fecha de nacimiento")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime fecha_nacimiento { get; set; }

        public decimal sueldo { get; set; }
    }
}

avanceCsharp/Models/Producto.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace avanceCsharp.Models
{
    [Table("tb_producto")]
    public class Producto
    {
        [Key]
        [Required(ErrorMessage = "El codigo es requerido")]
        [Display(Name = "Producto")]
        public string codigo_producto { get; set; }

        public required string producto { get; set; }

        [Display(Name = "Stock")]
        public int stock_disponible { get; set; }

        public decimal costo { get; set; } = 0.00M;

        public decimal ganancia { get; set; }

        [Display(Name = "Codigo marca")]
        public string producto_codigo_marca { get; set; }

        [Display(Name = "Codigo Categoria")]
        public string producto_codigo_categoria { get; set; }



    }
}

avanceCsharp/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;

namespace avanceCsharp.Controllers
{
    public class CategoriaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

avanceCsharp/Controllers/HomeController.cs
using avanceCsharp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace avanceCsharp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

avanceCsharp/Controllers/PersonalController.cs
using avanceCsharp.data;
using avanceCsharp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace avanceCsharp.Controllers
{
    public class PersonalController : Controller
    {

        private readonly ApplicationDbContext _context;

        public PersonalController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult Listar()
        {
            try
            {
                String cad_sql = "exec sp_listar_personal";
                List<Personal> arr_personal = _context.Personal.FromSqlRaw(cad_sql).ToList();
                return Json(new { data = arr_personal });
            }
            catch (Exception ex)
            {
                // Manejo de excepciones
                return Json(new { error = ex.Message });
            }
        }

        [HttpGet]
        public JsonResult Consultar(String dni)
        {
            String cad_sql = "exec sp_consultar_personal @dni";
            Personal? personal = new Personal();
            personal = _context.Personal.FromSqlRaw(cad_sql, new SqlParameter("@dni", dni)).ToList().FirstOrDefault();
            return Json(personal);
        }

        [HttpPost]
        public IActionResult Grabar([FromBody] Personal personal)
        {
            bool rpta = true;

            try
            {
                Personal? tmp_personal = null;

                tmp_personal = (from per in _context.Personal
                                where per.dni == personal.dni
                                select per).FirstOrDefault();

                if(tmp_personal == null)
                {
                    _context.Personal.Add(personal);
                    _context.SaveChanges();
                }
                else
                {
                    tmp_personal.ap_paterno = personal.ap_paterno;
                    tmp_personal.ap_materno = personal.ap_materno;
                    tmp_personal.nombre = personal.nombre;
                    tmp_personal.genero = personal.genero;
                    tmp_personal.fecha_nacimiento = personal.fecha_nacimiento;
                    tmp_personal.sueldo = personal.sueldo;

                    _context.SaveChanges();
                }

            }catch (Exception ex)
            {
                rpta = false;
            }

            return Json(new {resultado = rpta});
        }

        public JsonResult Borrar(String dni)
        {
            bool rpta = true;

            try
            {
                Personal? personal = new Personal();

                personal = (from per in _context.Personal
                                where per.dni == dni
                                select per).FirstOrDefault();

                _context.Personal.Remove(personal);
                _context.SaveChanges();
            }
            catch (Exception ex)
            {
                rpta = false;
            }

            return  Json(new {resultado = rpta});
        }
    }
}

avanceCsharp/Controllers/ProductoController.cs
using avanceCsharp.data;
using avanceCsharp.Models;
using Microsoft.AspNetCore.Mvc;

namespace avanceCsharp.Controllers
{
    public class ProductoController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductoController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            IEnumerable<Producto> ListarProducto = _context.Producto;

            return View(ListarProducto);
        }
    }
}

avanceCsharp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

avanceCsharp/Views/Personal/Index.cshtml
@model avanceCsharp.Models.Personal

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section EstiloDT {
    <link rel="stylesheet" href="~/lib/datatables.net/css/jquery.dataTables.min.css" />
}

<h1><i class="fas fa-university"></i>Listado de personal</h1>
<hr />

<div class="container">
    <div class="row mt-3">
        <table id="tb_personal" class="table table-striped display" style="width:100%">
            <thead>
                <tr>
                    <td>@Html.DisplayNameFor(per => per.dni)</td>
                    <td>@Html.DisplayNameFor(per => per.ap_paterno)</td>
                    <td>@Html.DisplayNameFor(per => per.ap_materno)</td>
                    <td>@Html.DisplayNameFor(per => per.nombre)</td>
                    <td>@Html.DisplayNameFor(per => per.genero)</td>
                    <td>@Html.DisplayNameFor(per => per.fecha_nacimiento)</td>
                    <td>@Html.DisplayNameFor(per => per.sueldo)</td>
                    <td>Acciones</td>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="formulario" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-12">
                        <form>
                            <div class="form-group">
                                <label asp-for="dni" class="control-label"></label>
                                 <input asp-for="dni" class="form-control"/>
                                 <span asp-validation-for="dni" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ap_materno" class="control-label"></label>
                                 <input asp-for="ap_materno" class="form-control"/>
                                 <span asp-validation-for="ap_materno" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ap_paterno" class="control-label"></label>
                                <input asp-for="ap_paterno" class="form-control" />
                                <span asp-validation-for="ap_paterno" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="nombre" class="control-label"></label>
                                <input asp-for="nombre" class="form-control" />
                                <span asp-validation-for="nombre" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="genero" class="control-label"></label>
                                <select asp-for="genero" class="form-control">
                                    <option value="">Seleccione un Género</option>
                                    <option value="F">Femenino</option>
                                    <option value="M">Masculino</option>
                                </select>
                                <span asp-validation-for="genero" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="fecha_nacimiento" class="control-label"></label>
                                <input asp-for="fecha_nacimiento" class="form-control" />
                                <span asp-validation-for="fecha_nacimiento" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="sueldo" class="control-label"></label>
                                <input asp-for="sueldo" class="form-control" />
                                <span asp-validation-for="sueldo" class="text-danger"></span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="btn_cerrar" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" id="btn_grabar" class="btn btn-primary"></button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/lib/datatables.net/js/jquery.dataTables.js"></script>
    <script src="~/lib/datatables.net/js/dataTables.buttons.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#tb_personal").DataTable({
                "ajax": {
                    "url": "@Url.Action("Listar", "Personal")",
                    "type": "GET",
                    "dataType": "json"
                },
                "columns": [
                    { "data": "dni" },
                    { "data": "ap_paterno" },
                    { "data": "ap_materno" },
                    { "data": "nombre" },
                    { "data": "genero" },
                    { "data": "fecha_nacimiento" },
                    { "data": "sueldo" },
                    {
                        "data": "dni",
                        "render": function (data) {
                            return "<button class='btn btn-outline-success' type='button' onclick='AbrirRegistro(" + data + ")'><i class='far fa-edit'></i></button>" +
                                "<button class='btn btn-outline-danger' type='button' onclick='Eliminar(" + data + ")'><i class='fas fa-trash-alt'></i></button>";
                        }
                    }
                ],
                "order": [[1, "asc"]],
                dom: "Bfrtip",
                buttons: [
                    {
                        text: "Registrar Personal",
                        attr: { class: "btn btn-outline-primary" },
                        action: function () {
                            AbrirRegistro("")
                        }
                    }
                ]
            });
        });

        function AbrirRegistro($dni) {
            if ($dni != "") {
                jQuery.ajax({
                    url: "@Url.Action("Consultar", "Personal")" + "?dni=" + $dni,
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        let fn = data.fecha_nacimiento.substring(0, 10);

                        if (data != null) {
                            $("#dni").attr("readonly", true);

                            $("#dni").val(data.dni);
                            $("#ap_paterno").val(data.ap_paterno);
                            $("#ap_materno").val(data.ap_materno);
                            $("#nombre").val(data.nombre);
                            $("#genero").val(data.genero);
                            $("#fecha_nacimiento").val(fn);
                            $("#sueldo").val(data.sueldo);
                        }
                    }
                });
                $(".modal-title").text("Editar personal");
                $("#btn_grabar").html("<i class='fas fa-save'></i>Guardar Cambios");
            } else {
                $("#dni").attr("readonly", false);

                $("#dni").val("");
                $("#ap_paterno").val("");
                $("#ap_materno").val("");
                $("#nombre").val("");
                $("#genero").val("");
                $("#fecha_nacimiento").val("");
                $("#sueldo").val("");

                $(".modal-title").text("Registrar personal");
                $("#btn_grabar").html("<i class='fas fa-save'></i>Guardar Datos");
            }

            $("#formulario").modal("show");
        }

        $("#btn_grabar").click(function (e) {
            let $personal = {
                "dni": $("#dni").val(),
                "ap_paterno": $("#ap_paterno").val(),
                "ap_materno": $("#ap_materno").val(),
                "nombre": $("#nombre").val(),
                "genero": $("#genero").val(),
                "fecha_nacimiento": $("#fecha_nacimiento").val(),
                "sueldo": $("#sueldo").val(),
            };

            jQuery.ajax({
                url: "@Url.Action("Grabar", "Personal")",
                type: "POST",
                data: JSON.stringify($personal),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    if (data.resultado) {
                        $("#tb_personal").DataTable().ajax.reload();
                        $("#formulario").modal("hide");
                    } else {
                        alert("No fue posible grabar la información.");
                    }
                },
                error: function (error) {
                    alert(error);
                }
            });
        });

        function Eliminar($dni) {
            if (confirm("Seguro de desea Eliminar?")) {
                jQuery.ajax({
                    url: "@Url.Action("Borrar", "Personal")" + "?dni=" + $dni,
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        if (data.resultado) {
                            $("#tb_personal").DataTable().ajax.reload();
                        }
                    } 
                });
            }
        }

    </script>
}

avanceCsharp/Views/Producto/Index.cshtml
@model IEnumerable<avanceCsharp.Models.Producto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-3 mb-2">
            <a class="btn btn-success" asp-controller="Producto"
            asp-action="Create">Agregar Producto</a>
        </div>
    </div>

    <div class="row">
        @if (Model.Count() > 0)
        {
            <table class="table table-striped">
                <thead>
                    <tr>
                        <td>@Html.DisplayNameFor(pro => pro.codigo_producto)</td>
                        <td>@Html.DisplayNameFor(pro => pro.producto)</td>
                        <td>@Html.DisplayNameFor(pro => pro.stock_disponible)</td>
                        <td>@Html.DisplayNameFor(pro => pro.costo)</td>
                        <td>@Html.DisplayNameFor(pro => pro.ganancia)</td>
                        <td>@Html.DisplayNameFor(pro => pro.producto_codigo_marca)</td>
                        <td>@Html.DisplayNameFor(pro => pro.producto_codigo_categoria)</td>
                        <td>Acciones</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var reg in Model)
                    {
                        <tr>
                            <td>@reg.codigo_producto</td>
                            <td>@reg.producto</td>
                            <td>@reg.stock_disponible</td>
                            <td>@reg.costo</td>
                            <td>@reg.ganancia</td>
                            <td>@reg.producto_codigo_marca</td>
                            <td>@reg.producto_codigo_categoria</td>
                            <td>
                                <a class="btn btn-outline-warning btn-sm" asp-controller="Producto"
                                   asp-action="Edit" asp-route-id="@reg.codigo_producto"><i class="fas fa-edit"></i>Editar</a>
                                <a class="btn btn-outline-danger btn-sm" asp-controller="Producto"
                                   asp-action="Delete" asp-route-id="@reg.codigo_producto"><i class="fas fa-trash-alt"></i>Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No existen registros</p>
        }
    </div>
</div>

avanceCsharp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - avanceCsharp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/avanceCsharp.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" asp-append-version="true" />
        
    @await RenderSectionAsync("EstiloDT", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">avanceCsharp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Producto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personal" asp-action="Index">Personal</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


        <div class="row">
            <div class="col-md-12">
                <footer class="footer mt-5">
                    <div class="container nav justify-content-center border-bottom pb-3 mb-3s">
                        <span class="text-muted">© 2024 Desarollado por Luis Lopez</span>
                    </div>
                </footer>
            </div>
        </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>